Personal/vthapar/assignment1
thapar-vansh/Intern-Assignment-1 pull request #2
Opened 2022-02-15 13:13 UTC by thapar-vansh

2022-02-15 13:14 UTC, jagdishcm-sixer requested changes

2022-02-15 13:14 UTC, jagdishcm-sixer commented on controllers/admin.js
> +    } catch (err) {
send response as well

2022-02-22 11:55 UTC, Sachin-R-Yawalkar requested changes

2022-02-22 11:55 UTC, jagdishcm-sixer requested changes

2022-02-22 11:55 UTC, Sachin-R-Yawalkar commented on controllers/admin.js
> +    throw new Error('Error deleting player')
No need to throw here

2022-02-22 11:55 UTC, jagdishcm-sixer commented on controllers/admin.js
> +      res.send('Player added')
you can use return res.send here and then put line 11 out of else block. In this way, you can eliminate nesting.

2022-02-22 11:55 UTC, Sachin-R-Yawalkar commented on controllers/index.js
> +    throw new Error('Error getting players')
No need to throw here

2022-02-22 11:55 UTC, jagdishcm-sixer commented on controllers/admin.js
> +      res.send('Player not found')
Use appropriate status codes while sending responses.

2022-02-22 11:55 UTC, jagdishcm-sixer commented on controllers/index.js
> +    const result = await indexServices.loginService(username, password)
Nice work with bcrypt. But this try block can be wrapped in single loginService function call and responses can be sent from loginService function itself.

2022-02-22 11:55 UTC, Sachin-R-Yawalkar commented on controllers/admin.js
> +export default {
You can just use 
`export default {
  addPlayers,
  updatePlayers,
  deletePlayers
}`

2022-02-22 11:55 UTC, Sachin-R-Yawalkar commented on controllers/admin.js
> +    throw new Error('Error updating player')
No need to throw here

2022-02-22 11:55 UTC, Sachin-R-Yawalkar commented on controllers/admin.js
> +    throw new Error('Error adding new player')
No need to throw here. Only throw errors from the try block.
Also you can send response here with some generic message like - 'Something went wrong'

2022-02-22 11:55 UTC, jagdishcm-sixer commented on middleware/auth.js
> +    req.user = decoded
check this decoded id/username in the database if it exists or not.

2022-02-22 11:55 UTC, Sachin-R-Yawalkar commented on services/indexServices.js
> +dotenv.config()
No need to add this in every file

2022-03-01 12:17 UTC, Sachin-R-Yawalkar requested changes

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on controllers/admin.js
> +    throw new Error('Error updating player')
Why?

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on controllers/admin.js
> +    throw new Error('Error deleting player')
Why error if the operation is done?

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on controllers/index.js
> +    throw new Error('Error getting players')
No need to throw here

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on controllers/admin.js
> +    const player = await getPlayerByNameService(name)
action: `getPlayerByName`

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on controllers/admin.js
> +    throw new Error('Error adding new player')
No need to add throw here since you are already sending the response from line 17

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on controllers/index.js
> +    console.log(e)
in case of error you should send some response

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on controllers/user.js
> +  const { id } = req.body
what if the id is null or undefined?

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on services/indexServices.js
> +    const hashedPassword = await bcrypt.hash(password, 10)
what if password is blank?

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on controllers/index.js
> +  const { username, password } = req.body
what if username or password is blank? add some validations

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on controllers/index.js
> +    throw new Error('Error getting players')
Why would someone get this error message while registering?

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on controllers/user.js
> +    res.send(favPlayer)
action: Add res.status(200).send(...)

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on database/players.db.js
> +  return result.rowCount > 0 ? result.rows[0] : []
in case you are only sending a particular row, you should send null or throw error, otherwise for blank array you will have to add length check along with null check

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on database/players.db.js
> +  return result.rowCount > 0 ? result.rows[0] : []
same

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on database/users.db.js
> +    `SELECT * FROM users
Check and try to implement [this](https://www.geeksforgeeks.org/sql-exists/)

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on routes/adminRoutes.js
> +router.post('/update/players', verifyAdmin, updatePlayers)
router.put(..

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on routes/adminRoutes.js
> +router.post('/delete/players', verifyAdmin, deletePlayers)
router.delete(..

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on services/adminServices.js
> +    throw new Error('Error adding new player')
This will always go in catch and will just be logged, and from the controller you will be sending success.

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on controllers/admin.js
> +    console.log(e)
You will never get any response from here

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on services/indexServices.js
> +export const loginService = async (username, password, req, res) => {
you can destruct username, password from req object then why to use it seperately?

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on services/indexServices.js
> +  const userId = req.user.userId
you can destruct userId from the controller itself

2022-03-01 12:17 UTC, Sachin-R-Yawalkar commented on services/userServices.js
> +  try {
Remove all try catch from service files and keep them only in controllers

2022-03-04 12:52 UTC, jagdishcm-sixer requested changes

2022-03-04 12:52 UTC, jagdishcm-sixer commented on controllers/index.js
> +    throw new Error('Error getting players')
No need to throw error after sending success response. Add status to the response as well.

2022-03-04 12:52 UTC, jagdishcm-sixer commented on controllers/index.js
> +export const login = async (req, res, next) => {
no need of next function since it's not a middleware.

2022-03-04 12:52 UTC, jagdishcm-sixer commented on controllers/admin.js
> +} from '../services/adminServices.js'
name of the file should be adminService.js

2022-03-04 12:52 UTC, jagdishcm-sixer commented on controllers/admin.js
> +      await addPlayerService(name, country)
name of the function should be addPlayer

2022-03-04 12:52 UTC, jagdishcm-sixer commented on controllers/admin.js
> +    console.log(e)
Send generic error from catch block like `res.status(400).send('Something went wrong')`

2022-03-04 12:52 UTC, jagdishcm-sixer commented on controllers/user.js
> +    if (favPlayer && favPlayer.length === 0) {
instead you can write this line as  if (favPlayer?.length === 0) {

2022-03-04 12:52 UTC, Sachin-R-Yawalkar requested changes

2022-03-04 12:52 UTC, Sachin-R-Yawalkar commented on controllers/index.js
> +    await loginService(req, res)
Send response from the controller. No need to send `req, res` objects to the service.

2022-03-04 12:52 UTC, Sachin-R-Yawalkar commented on routes/indexRoutes.js
> +router.post('/login', verifyUser, login)
Why are you using post here?

2022-03-07 07:59 UTC, thapar-vansh commented on routes/indexRoutes.js
> +router.post('/login', verifyUser, login)
done

2022-03-07 08:00 UTC, thapar-vansh commented on controllers/index.js
> +    await loginService(req, res)
done

2022-03-07 08:00 UTC, thapar-vansh commented on controllers/user.js
> +    if (favPlayer && favPlayer.length === 0) {
done

2022-03-07 08:00 UTC, thapar-vansh commented on controllers/admin.js
> +    console.log(e)
done

2022-03-07 08:01 UTC, thapar-vansh commented on middleware/auth.js
> +    req.user = decoded
done

2022-03-07 08:02 UTC, thapar-vansh commented on controllers/admin.js
> +      await addPlayerService(name, country)
done

2022-03-07 08:03 UTC, thapar-vansh commented on controllers/admin.js
> +} from '../services/adminServices.js'
done

2022-03-07 08:03 UTC, thapar-vansh commented on controllers/index.js
> +export const login = async (req, res, next) => {
done

2022-03-09 13:39 UTC, jagdishcm-sixer requested changes
- Update & delete players ( handling of invalid id)

- Add favorites invalid id handling

- User login error handling with invalid password

2022-03-10 16:00 UTC, thapar-vansh commented
> 

Added password validation
Handled the invalid id for respective functions
Fixed error messages

2022-03-11 12:46 UTC, jagdishcm-sixer approved these changes

2022-03-11 12:47 UTC, jagdishcm-sixer commented
Good work buddy

2022-03-11 13:04 UTC, Sachin-R-Yawalkar approved these changes
Good one :)

2022-03-11 13:07 UTC, merged